spring:
  rabbitmq:
    username: feng
    password: feng
    port: 5672
    cache:
      channel:
        size: 100
    host: rabbitmq
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.40.128:3306/cloud?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: feng