spring:
  rabbitmq:
    username: feng
    password: feng
    port: 5672
    host: rabbitmq
    cache:
      channel:
        size: 100

server:
  port: 8060

management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

#zuul:
#  ignoredServices: '*'
#  routes:
#    auth-service:
#      path: /uaa/**
#      stripPrefix: false
#      sensitiveHeaders:
#    svca-service:
#      path: /svca/**
#      sensitiveHeaders:
#    svcb-service:
#      path: /svcb/**
#      sensitiveHeaders:

