spring:
  rabbitmq:
    username: feng
    password: feng
    port: 5600
    host: rabbitmq
    cache:
      channel:
        size: 100

server:
  port: 8070

msg: Hello

security:
  oauth2:
    client:
      clientId: svcb-service
      clientSecret: ${security.user.password}
      accessTokenUri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/oauth/token
      grant-type: client_credentials
      scope: server

