spring:
  rabbitmq:
    username: feng
    password: feng
    port: 5672
    host: rabbitmq
    cache:
      channel:
        size: 100

server:
  port: 8070

msg: Hello

security:
  oauth2:
    client:
      clientId: svcb-service
      clientSecret: ${security.user.password}
      accessTokenUri: http://${auth.hostname}:${auth.port}${auth.contextPath}/oauth/token
      grant-type: client_credentials
      scope: server
#    resource:
#      user-info-uri: http://${auth.hostname}:${auth.port}${auth.contextPath}/current
#
#auth:
#  hostname: auth-service
#  port: 5000
#  contextPath: /uaa

