spring:
  rabbitmq:
    username: feng
    password: feng
    port: 5672
    cache:
      channel:
        size: 100
    host: rabbitmq

server:
  port: 8080

name: feng

security:
  oauth2:
    client:
      clientId: svca-service
      clientSecret: ${security.user.password}
      accessTokenUri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/oauth/token
      grant-type: client_credentials
      scope: server

